In [2]:
import numpy as np

In [6]:
my_list=[1,2,3,4]

In [7]:
my_array1=np.array(my_list)

In [8]:
my_array1


array([1, 2, 3, 4])

In [9]:
my_list2=[11,22,33,44
         ]

In [10]:
my_array2=np.array(my_list2)

In [11]:
my_array2


array([11, 22, 33, 44])

In [12]:
my_lists=[my_list,my_list2
         ]

In [13]:

my_lists


[[1, 2, 3, 4], [11, 22, 33, 44]]

In [14]:
np.array(my_lists)

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [15]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [16]:
np.ones([5,5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [17]:
np.eye(10)


array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [18]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [19]:
np.arange(5,50,3
         )

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [20]:
5/2


2

In [21]:
5.0/2


2.5

In [22]:
a1=np.array([[1,2,3,4],[8,9,10,11]])

a1*a1


In [23]:
a1*a1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [24]:
a1-a1


array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [25]:
from __future__ import division


In [26]:
a1/a1


array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [27]:
np.eye(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [28]:
a1/np.eye(4)

ValueError: operands could not be broadcast together with shapes (2,4) (4,4) 

In [29]:
a1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [30]:
a1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [31]:
a1[0][2]

3

In [33]:
a1[:1][:3]

array([[1, 2, 3, 4]])

In [34]:
arr_len=a1.shape[1]

In [35]:
arr_len


4

In [37]:
a1.shape[1]

4

In [38]:
a1[0]

array([1, 2, 3, 4])

In [39]:
a1[1
  ]

array([ 8,  9, 10, 11])

In [4]:
arr=np.arange(50).reshape((10,5))


In [5]:
arr


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [6]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [7]:
np.dot(arr.T,arr)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [8]:
arr3d=np.arange(50).reshape((5,5,2))

In [9]:
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [10]:
arr3d.T

array([[[ 0, 10, 20, 30, 40],
        [ 2, 12, 22, 32, 42],
        [ 4, 14, 24, 34, 44],
        [ 6, 16, 26, 36, 46],
        [ 8, 18, 28, 38, 48]],

       [[ 1, 11, 21, 31, 41],
        [ 3, 13, 23, 33, 43],
        [ 5, 15, 25, 35, 45],
        [ 7, 17, 27, 37, 47],
        [ 9, 19, 29, 39, 49]]])

Universal Array Functions 

In [12]:
arr=np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [14]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [15]:
A=np.random.randn(10)

A

array([-1.06763671, -1.17353566,  1.19457159,  0.34500044, -0.51989546,
       -0.25021288, -0.00175836, -0.58275663,  1.23562908, -0.61715789])

In [18]:
B=np.random.randn(10)

In [19]:
B

array([-0.87006621,  0.90166074, -1.95239362,  0.25042894, -0.35109682,
        0.61115527, -0.80943365, -0.27818527, -2.02267461, -0.87623534])

In [20]:
np.add(A,B)

array([-1.93770291, -0.27187492, -0.75782204,  0.59542939, -0.87099228,
        0.36094239, -0.81119201, -0.8609419 , -0.78704553, -1.49339323])

In [21]:
np.maximum(A,B)

array([-0.87006621,  0.90166074,  1.19457159,  0.34500044, -0.35109682,
        0.61115527, -0.00175836, -0.27818527,  1.23562908, -0.61715789])

In [22]:
np.minimum(A,B)

array([-1.06763671, -1.17353566, -1.95239362,  0.25042894, -0.51989546,
       -0.25021288, -0.80943365, -0.58275663, -2.02267461, -0.87623534])